#!/bin/bash

echo "🔧 MongoDB Connection String Fixer"
echo "=================================="

echo "The backend is failing because the MongoDB connection string needs proper URL encoding."
echo ""
echo "📋 Steps to fix:"
echo ""
echo "1. Go to MongoDB Atlas: https://www.mongodb.com/atlas"
echo "2. Create a free cluster (if not done)"
echo "3. Create a database user:"
echo "   - Username: cryptogig"
echo "   - Password: Use ONLY letters and numbers (no special characters)"
echo "   - Example good password: CryptoGig123"
echo ""
echo "4. Set Network Access to 0.0.0.0/0 (Allow access from anywhere)"
echo ""
echo "5. Get connection string:"
echo "   - Go to Connect → Connect your application"
echo "   - Copy the connection string"
echo "   - Replace <password> with your actual password"
echo "   - Replace <dbname> with: cryptogig_db"
echo ""
echo "6. Update Railway with the connection string:"
echo "   cd backend"
echo "   railway variables --set \"MONGO_URL=mongodb+srv://cryptogig:YourPassword@cluster0.xxxxx.mongodb.net/cryptogig_db?retryWrites=true&w=majority\""
echo ""
echo "Example of correct connection string:"
echo "mongodb+srv://cryptogig:CryptoGig123@cluster0.abc123.mongodb.net/cryptogig_db?retryWrites=true&w=majority"
echo ""
echo "❌ AVOID special characters in password like: @, #, $, %, &, etc."
echo "✅ USE only: letters, numbers, and basic characters"